[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (if needed for CORS)
[[redirects]]
  from = "/api/*"
  to = "https://ai-resume-builder-backend-uhdm.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
